services:
  - type: web
    name: symfony-app
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php bin/console cache:clear
    envVars:
      - key: APP_ENV
        value: prod
