services:
  - type: web
    name: symfony-app
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php bin/console cache:clear
    startCommand: |
      php -S 0.0.0.0:8000 -t public
